# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloc < Formula
  desc "CLI to discover and run local AI models using community recipes"
  homepage "https://bloc-theta.vercel.app/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_darwin_amd64.tar.gz"
      sha256 "fcb76decb970b91c4dbb9c0721cb4b42b977faf030c8ec3722e2798b59536ac2"

      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_darwin_arm64.tar.gz"
      sha256 "e3697580b012d1b493137a6378dd9e2d44fac2bc9798a49360cca509c7941740"

      def install
        bin.install "bloc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_linux_amd64.tar.gz"
      sha256 "f40167ec2980052b28212140015186cd798bd25979ee642fabc2e78adeb859e7"
      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_linux_arm64.tar.gz"
      sha256 "8afcf45b05ee666c283f617677df2f9a0c7ffb840f9133e06f3a8a9cd8c28a16"
      def install
        bin.install "bloc"
      end
    end
  end
end
