# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloc < Formula
  desc "CLI to discover and run local AI models using community recipes"
  homepage "https://bloc-theta.vercel.app/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_darwin_amd64.tar.gz"
      sha256 "8974d5e20d2eb36cf5101ab5de02a92ed6017eca5e562d22bb16a4a29216491e"

      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_darwin_arm64.tar.gz"
      sha256 "e3e012800f69d9e342c359b914843048ff4e7f15aa541618ae8e092ad9232fac"

      def install
        bin.install "bloc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_linux_amd64.tar.gz"
      sha256 "69f036f5c908c463dc67f64425118316ce88f79cc940b4f4611577d2d307f002"
      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arnav080/Bloc/releases/download/v0.1.0/bloc_linux_arm64.tar.gz"
      sha256 "961254a08df93721526e5d55aa84f8d0097aa51757b5ccbebd833c84f0ac7a1c"
      def install
        bin.install "bloc"
      end
    end
  end
end
