# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloc < Formula
  desc "CLI to discover and run local AI models using community recipes"
  homepage "https://bloc-theta.vercel.app/"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.3.0/bloc_darwin_amd64.tar.gz"
      sha256 "5ae42e5af9cb1ed5fba81ceb964a3274e05d6b5a6fbf279335fbe97438505ed1"

      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.3.0/bloc_darwin_arm64.tar.gz"
      sha256 "9810915bb1221489ca5557dd82f1f11f2769fe803bc405073d80ff9561ec7bc0"

      def install
        bin.install "bloc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.3.0/bloc_linux_amd64.tar.gz"
      sha256 "9d6edd3ad7d2040a10fe37f9d3d574fcd8727df959f2da9c680aee1b8eb7ed8e"
      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.3.0/bloc_linux_arm64.tar.gz"
      sha256 "8134b221cb2ebc31bd623d4bbafce600e9cef7ed6a469c7a53063a4ee39a2243"
      def install
        bin.install "bloc"
      end
    end
  end
end
